### ISSUE TITLE
MacBook M1 无法打开“portal”，因为无法验证开发者。

### ISSUE THREAD

**Issue by chaosgpt** [lxfater/Portal#11]
请问如何解决这个issue

**Comment by lxfater** [comment]
目前没有进行签名，可以的话放开限制就好了。你可以谷歌如何解除限制。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 下午2:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lxfater/Portal] MacBook M1 无法打开“portal”，因为无法验证开发者。 (Issue #11)




 
请问如何解决这个issue

**Comment by chaosgpt** [comment]
谢谢您的快速回复，问题已解决
