### ISSUE TITLE
每次按了快捷键，portal窗口都会弹出来，挡住了程序窗口

### ISSUE THREAD

**Issue by xinde** [lxfater/Portal#14]
不知道是不是设置问题，每次按了快捷键，portal窗口都会弹出来，挡住了程序窗口，并没有像视频中那样丝滑的覆盖选中的句子，这是我的配置
![image](https://user-images.githubusercontent.com/1617414/228408690-a40f0326-3ae1-489b-b1e8-be7c4e5aa3dd.png)

**Comment by lxfater** [comment]
关闭调转到鼠标处



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月29日(周三) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lxfater/Portal] 每次按了快捷键，portal窗口都会弹出来，挡住了程序窗口 (Issue #14)




 
不知道是不是设置问题，每次按了快捷键，portal窗口都会弹出来，挡住了程序窗口，并没有像视频中那样丝滑的覆盖选中的句子，这是我的配置

**Comment by xinde** [comment]
> 关闭调转到鼠标处
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月29日(周三) 上午10:14 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [lxfater/Portal] 每次按了快捷键，portal窗口都会弹出来，挡住了程序窗口 (Issue #14) 不知道是不是设置问题，每次按了快捷键，portal窗口都会弹出来，挡住了程序窗口，并没有像视频中那样丝滑的覆盖选中的句子，这是我的配置 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谢谢
