### ISSUE TITLE
最小化到系统托盘

### ISSUE THREAD

**Issue by huhusmang** [lxfater/Portal#20]
叉掉的时候，能不能选择最小化到系统托盘，经常容易退出

**Comment by lxfater** [comment]
在做了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月30日(周四) 晚上7:42
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lxfater/Portal] 最小化到系统托盘 (Issue #20)




 
叉掉的时候，能不能选择最小化到系统托盘，经常容易退出
