### ISSUE TITLE
如何记住上下文连续聊天呢？

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [lxfater/Portal#5]
有时候答案比较长没有回答完，让他接着说，回答的内容和上一个完全不是一回事。

我试了用 `与当前对话创建连接` 但是没有效果。

目前暂时的解决方案：我把token数目调到了最大的2048。

**Comment by lxfater** [comment]
目前apikey还不支持连续上下文，只有chatgptWeb才支持，后续会支持。体验可以使用小号体验Web方式。@CoffeeDrinkRabbit
