### ISSUE TITLE
能否让直通模式同步输入的内容不要出现在剪贴板历史中

### ISSUE THREAD

**Issue by cicav** [lxfater/Portal#7]
能否让直通模式同步输入的内容不要出现在剪贴板历史中，现在这样会让剪贴板内容非常混乱。如图
![CleanShot 2023-03-27 at 21 50 24@2x](https://user-images.githubusercontent.com/19179979/227959232-36f6dcd7-2ab0-4cd9-b52d-4c3af95831cc.jpg)

**Comment by lxfater** [comment]
可以，关闭光标处写入，就能解决了

**Comment by dimmiyjy** [comment]
希望能保留光标处写入，同时不让内容同步到剪贴板中，请问有办法吗？

**Comment by cicae** [comment]
> 可以，关闭光标处写入，就能解决了
希望能保留光标处写入，同时不让内容同步到剪贴板中，请问有办法吗？

**Comment by lxfater** [comment]
有办法，进群来说吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月27日(周一) 晚上10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lxfater/Portal] 能否让直通模式同步输入的内容不要出现在剪贴板历史中 (Issue #7)




  
可以，关闭光标处写入，就能解决了
 希望能保留光标处写入，同时不让内容同步到剪贴板中，请问有办法吗？
